// <auto-generated />
namespace RecipesAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Datos02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datos02));
        
        string IMigrationMetadata.Id
        {
            get { return "202003101811019_Datos02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
